로그인 Api 구현 및 비밀번호 인코딩
su-dong-dev/couple-sns pull request #8
Opened 2023-01-31 08:13 UTC by tudiiii

2023-01-31 18:23 UTC, pointehd commented on src/main/java/com/couple/sns/common/configuration/AuthenticationConfig.java
> +                .formLogin().and()
`.formLogin().disable()` 이런형태로 많이 쓴거같은데 이거도 잘되나용?

2023-01-31 18:29 UTC, pointehd commented on src/main/java/com/couple/sns/common/configuration/filter/JwtTokenFilter.java
> +            User user = userUpdateService.loadUserByUserId(userId);
토큰인증 확인 > 토큰 정보 추출 > db 정보 확인 > user 정보 > SecurityContext에 저장
프로세스가 이렇게 보이는데 db 접속 정보를 확인할경우 jwt에 대한 큰 메리트는 사라지는게 아닐까 생각하는데 어떻게 생각하시나요?

2023-01-31 18:31 UTC, pointehd commented on src/main/java/com/couple/sns/common/configuration/filter/JwtTokenFilter.java
> +            filterChain.doFilter(request, response);
에러 발생시킬 경우 errorHandler를 security config 쪽에 달아줘야 원하는 메시지로 리턴 할수 있을텐데 코드 확인이안되용

2023-01-31 18:32 UTC, pointehd commented on src/main/java/com/couple/sns/domain/user/dto/response/UserLoginResponse.java
> +    private String token;
리프레시 토큰으로 재발급 과정도 나중에 추가되면 좋을것 같습니다.

2023-01-31 18:33 UTC, pointehd commented on src/main/resources/application.yml
> +    #      naming:
의미없는 주석은 삭제하면 좋을듯요 ( 제 생각 )

2023-01-31 18:35 UTC, pointehd commented on src/main/resources/application.yml
> +  expired-time-ms: 2592000000
리프레시 토큰으로 재발급 과정이 필요해요 토큰 시간이 너무 긴것 같아요

2023-01-31 18:37 UTC, pointehd requested changes
테스트 코드는 저보다 잘짜서 할말이 없숨다... 아주 열심히 하는게 보기 좋아요 저도 분발하겠숨다

2023-02-01 08:56 UTC, tudiiii commented on src/main/java/com/couple/sns/common/configuration/AuthenticationConfig.java
> +                .formLogin().and()
@pointehd 잘됩니다 ! 기본 로그인페이지가 필요없으니깐 말씀해주신 disable() 로 수정하겠습니다 ~

2023-02-01 13:33 UTC, tudiiii commented on src/main/java/com/couple/sns/domain/user/dto/response/UserLoginResponse.java
> +    private String token;
@pointehd 리프레시 토큰 추가는 따로 이슈 추가하겠습니다 !

2023-02-01 13:33 UTC, tudiiii commented on src/main/resources/application.yml
> +  expired-time-ms: 2592000000
@pointehd 리프레시 토큰 추가는 따로 이슈 추가하겠습니다 !

2023-02-05 13:26 UTC, tudiiii commented on src/main/resources/application.yml
> +    #      naming:
@pointehd 넵 😁

2023-02-05 14:28 UTC, tudiiii commented on src/main/java/com/couple/sns/common/configuration/filter/JwtTokenFilter.java
> +            User user = userUpdateService.loadUserByUserId(userId);
@pointehd 확인해보니 디비에 접근해서 userId 판단 유무를 하지 않고, 토큰이 유효한 토큰인지 판단하는 과정만 필요한 것 같아서 소스 코 드 수정하였습니다

2023-02-05 14:29 UTC, tudiiii commented on src/main/java/com/couple/sns/common/configuration/filter/JwtTokenFilter.java
> +            filterChain.doFilter(request, response);
@pointehd 필터내에서 발생한 예외를 처리해줘야하는 부분이 작성되지 않은 것 같아서 jwt 리프레쉬 토큰 발급과 같이 이슈에 추가하였습니다 ! 감사합니다 ☺️

2023-02-21 04:39 UTC, pointehd approved these changes
머지하세용

2023-02-21 04:39 UTC, merged